#requires -PSEdition Core
#requires -Version 7.0
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$utf8 = [System.Text.UTF8Encoding]::new($false)
[Console]::InputEncoding = $utf8
[Console]::OutputEncoding = $utf8
$OutputEncoding = $utf8

# Load the shared managed text section helper used by section-owning conventions.
$configTextSectionPath = Join-Path $PSScriptRoot '..' '..' '..' 'conventions' 'scripts' 'ConfigTextSection.psm1'
Import-Module $configTextSectionPath

# Define the managed README table marker used by this convention.
$script:readmeConventionsSectionName = 'generated by .github/conventions/update-readme-conventions'
$script:legacyReadmeConventionsMarker = '<!-- DO NOT EDIT: generated by .github/conventions/update-readme-conventions -->'

# Return the first prose paragraph after the README title.
function GetFirstParagraph {
	param(
		[Parameter(Mandatory = $true)]
		[string] $Path
	)

	$content = [System.IO.File]::ReadAllText($Path)
	$lines = ($content -replace "`r`n", "`n" -replace "`r", "`n") -split "`n"
	$index = 0

	while ($index -lt $lines.Count -and [string]::IsNullOrWhiteSpace($lines[$index])) {
		$index++
	}

	if ($index -lt $lines.Count -and $lines[$index] -match '^#\s+') {
		$index++
	}

	while ($index -lt $lines.Count -and [string]::IsNullOrWhiteSpace($lines[$index])) {
		$index++
	}

	$paragraphLines = [System.Collections.Generic.List[string]]::new()

	while ($index -lt $lines.Count -and -not [string]::IsNullOrWhiteSpace($lines[$index])) {
		$paragraphLines.Add($lines[$index].Trim())
		$index++
	}

	if ($paragraphLines.Count -eq 0) {
		throw "No first paragraph was found in '$Path'."
	}

	return ($paragraphLines -join ' ')
}

# Rewrite relative markdown links so README descriptions work from the repository root.
function ConvertDescriptionLinks {
	param(
		[Parameter(Mandatory = $true)]
		[string] $Text,

		[Parameter(Mandatory = $true)]
		[string] $ReadmeDirectory,

		[Parameter(Mandatory = $true)]
		[string] $RepositoryRoot
	)

	return [System.Text.RegularExpressions.Regex]::Replace(
		$Text,
		'(?<Prefix>\[[^\]]+\]\()(?<Target>[^)]+)(?<Suffix>\))',
		{
			param($match)

			$target = $match.Groups['Target'].Value

			if ($target -match '^[A-Za-z][A-Za-z0-9+.-]*:' -or $target.StartsWith('#', [System.StringComparison]::Ordinal) -or $target.StartsWith('/', [System.StringComparison]::Ordinal)) {
				return $match.Value
			}

			$anchor = ''
			$targetPath = $target
			$anchorIndex = $target.IndexOf('#')

			if ($anchorIndex -ge 0) {
				$anchor = $target.Substring($anchorIndex)
				$targetPath = $target.Substring(0, $anchorIndex)
			}

			if ([string]::IsNullOrWhiteSpace($targetPath)) {
				return $match.Value
			}

			$resolvedPath = [System.IO.Path]::GetFullPath((Join-Path $ReadmeDirectory $targetPath))
			$relativePath = [System.IO.Path]::GetRelativePath($RepositoryRoot, $resolvedPath).Replace('\', '/')

			if (-not $relativePath.StartsWith('.', [System.StringComparison]::Ordinal)) {
				$relativePath = './' + $relativePath
			}

			return $match.Groups['Prefix'].Value + $relativePath + $anchor + $match.Groups['Suffix'].Value
		})
}

# Escape markdown table delimiters in generated cell content.
function ConvertTableCell {
	param(
		[Parameter(Mandatory = $true)]
		[string] $Text
	)

	return $Text.Replace('|', '\|')
}

# Build convention table entries from published convention directories.
function GetConventionEntries {
	param(
		[Parameter(Mandatory = $true)]
		[string] $RepositoryRoot
	)

	$conventionsRoot = Join-Path $RepositoryRoot 'conventions'

	if (-not (Test-Path -LiteralPath $conventionsRoot -PathType Container)) {
		throw "The conventions directory was not found at '$conventionsRoot'."
	}

	$entries = [System.Collections.Generic.List[object]]::new()

	foreach ($conventionDirectory in Get-ChildItem -LiteralPath $conventionsRoot -Directory | Sort-Object -Property Name) {
		$readmePath = Join-Path $conventionDirectory.FullName 'README.md'
		$conventionYamlPath = Join-Path $conventionDirectory.FullName 'convention.yml'
		$conventionScriptPath = Join-Path $conventionDirectory.FullName 'convention.ps1'

		if (-not (Test-Path -LiteralPath $readmePath -PathType Leaf)) {
			continue
		}

		if (-not ((Test-Path -LiteralPath $conventionYamlPath -PathType Leaf) -or (Test-Path -LiteralPath $conventionScriptPath -PathType Leaf))) {
			continue
		}

		$description = GetFirstParagraph -Path $readmePath
		$description = ConvertDescriptionLinks -Text $description -ReadmeDirectory $conventionDirectory.FullName -RepositoryRoot $RepositoryRoot

		$entries.Add([pscustomobject]@{
			Name = $conventionDirectory.Name
			Path = ('./conventions/' + $conventionDirectory.Name + '/README.md')
			Description = $description
		})
	}

	return $entries.ToArray()
}

# Render the README conventions table body.
function NewConventionsTable {
	param(
		[Parameter(Mandatory = $true)]
		[object[]] $Entries
	)

	# Start the managed content directly with the table so surrounding README prose is preserved.
	$lines = [System.Collections.Generic.List[string]]::new()
	$lines.Add('| Convention | Description |')
	$lines.Add('| --- | --- |')

	foreach ($entry in $Entries) {
		$name = ConvertTableCell -Text $entry.Name
		$description = ConvertTableCell -Text $entry.Description
		$lines.Add("| [$name]($($entry.Path)) | $description |")
	}

	return ($lines -join "`n")
}

function TestMarkdownTableLine {
	param(
		[Parameter(Mandatory = $true)]
		[AllowEmptyString()]
		[string] $Line
	)

	# Treat consecutive pipe-delimited lines after the legacy marker as the generated table.
	return $Line -match '^\|.*\|\s*$'
}

function GetTrailingLineEndingText {
	param(
		[Parameter(Mandatory = $true)]
		[AllowEmptyString()]
		[string] $Text
	)

	# Preserve the exact line ending that followed the legacy generated table span.
	if ($Text.EndsWith("`r`n", [System.StringComparison]::Ordinal)) {
		return "`r`n"
	}

	if ($Text.EndsWith("`n", [System.StringComparison]::Ordinal)) {
		return "`n"
	}

	if ($Text.EndsWith("`r", [System.StringComparison]::Ordinal)) {
		return "`r"
	}

	return ''
}

function NewManagedReadmeConventionsBlock {
	param(
		[Parameter(Mandatory = $true)]
		[string] $Table,

		[Parameter(Mandatory = $true)]
		[string] $LineEnding
	)

	# Normalize the generated table before wrapping it with the shared marker format.
	$normalizedTable = ($Table -replace "`r`n", "`n" -replace "`r", "`n").Replace("`n", $LineEnding)
	$blockText = "<!-- DO NOT EDIT: $script:readmeConventionsSectionName convention -->$LineEnding$normalizedTable"

	# Ensure the closing marker starts on its own line.
	if (-not $normalizedTable.EndsWith($LineEnding, [System.StringComparison]::Ordinal)) {
		$blockText += $LineEnding
	}

	# Close the managed README table block consistently with other conventions.
	$blockText += '<!-- END DO NOT EDIT -->'
	return $blockText
}

function ConvertLegacyReadmeConventionsBlock {
	param(
		[Parameter(Mandatory = $true)]
		[string] $Content,

		[Parameter(Mandatory = $true)]
		[string] $Table,

		[Parameter(Mandatory = $true)]
		[string] $LineEnding,

		[Parameter(Mandatory = $true)]
		[string] $TargetPath
	)

	# Locate the old single-marker block without interpreting surrounding README text as generated.
	$lineRecords = @(Get-ConfigTextSectionLineRecords -Content $Content)
	$legacyMarkerIndexes = [System.Collections.Generic.List[int]]::new()

	for ($index = 0; $index -lt $lineRecords.Count; $index++) {
		if ($lineRecords[$index].Text -eq $script:legacyReadmeConventionsMarker) {
			$legacyMarkerIndexes.Add($index)
		}
	}

	# Leave files that already use the paired managed marker to the shared section helper.
	if ($legacyMarkerIndexes.Count -eq 0) {
		return $Content
	}

	# Refuse to guess when a README has multiple legacy generated tables.
	if ($legacyMarkerIndexes.Count -gt 1) {
		throw "Found multiple legacy README conventions markers in '$TargetPath'."
	}

	# Include blank lines immediately after the legacy marker so the new table starts right after DO NOT EDIT.
	$startIndex = $lineRecords[$legacyMarkerIndexes[0]].StartIndex
	$endIndex = $lineRecords[$legacyMarkerIndexes[0]].EndIndex
	$index = $legacyMarkerIndexes[0] + 1

	while ($index -lt $lineRecords.Count -and [string]::IsNullOrWhiteSpace($lineRecords[$index].Text)) {
		$endIndex = $lineRecords[$index].EndIndex
		$index++
	}

	# Replace only the table rows after the marker, preserving following README content.
	while ($index -lt $lineRecords.Count -and (TestMarkdownTableLine -Line $lineRecords[$index].Text)) {
		$endIndex = $lineRecords[$index].EndIndex
		$index++
	}

	# Splice the paired managed block into the old table location.
	$currentBlockText = $Content.Substring($startIndex, $endIndex - $startIndex)
	$replacementBlockText = (NewManagedReadmeConventionsBlock -Table $Table -LineEnding $LineEnding) + (GetTrailingLineEndingText -Text $currentBlockText)
	return $Content.Substring(0, $startIndex) + $replacementBlockText + $Content.Substring($endIndex)
}

# Detect the line ending already used by the README.
function GetReadmeLineEnding {
	param(
		[Parameter(Mandatory = $true)]
		[AllowEmptyString()]
		[string] $Content
	)

	if ($Content.Contains("`r`n")) {
		return "`r`n"
	}

	return "`n"
}

# Build the managed text section settings for the root README conventions table.
function GetReadmeConventionsSettings {
	param(
		[Parameter(Mandatory = $true)]
		[string] $Table
	)

	# Return settings that let ConfigTextSection own add, replace, validation, and idempotency.
	return @{
		path = 'README.md'
		name = $script:readmeConventionsSectionName
		text = $Table
		'comment-prefix' = '<!--'
		'comment-suffix' = '-->'
	}
}

# Regenerate the root README conventions table.
$repositoryRoot = [System.IO.Path]::GetFullPath((Get-Location).Path)
$readmePath = Join-Path $repositoryRoot 'README.md'

if (-not (Test-Path -LiteralPath $readmePath -PathType Leaf)) {
	throw "The repository root README was not found at '$readmePath'."
}

$existingContent = [System.IO.File]::ReadAllText($readmePath)
$lineEnding = GetReadmeLineEnding -Content $existingContent
$entries = GetConventionEntries -RepositoryRoot $repositoryRoot
$table = NewConventionsTable -Entries $entries
$settings = GetReadmeConventionsSettings -Table $table

# Validate generated table text before migrating any legacy marker in the README.
Get-ConfigTextSectionText -TextSetting $table -CommentPrefix '<!--' -CommentSuffix ' -->' | Out-Null

# Convert the old single-marker table in place, then delegate normal section updates to the shared helper.
$newContent = ConvertLegacyReadmeConventionsBlock -Content $existingContent -Table $table -LineEnding $lineEnding -TargetPath $readmePath

if ($newContent -cne $existingContent) {
	[System.IO.File]::WriteAllText($readmePath, $newContent, $utf8)
	Write-Host "Updated 'README.md' with the current conventions table."
}

Invoke-ConfigTextSection -Settings $settings
