#requires -PSEdition Core
#requires -Version 7.0
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$utf8 = [System.Text.UTF8Encoding]::new($false)
[Console]::InputEncoding = $utf8
[Console]::OutputEncoding = $utf8
$OutputEncoding = $utf8

# Define the Pester suite for the update-readme-conventions convention.
Describe 'update-readme-conventions convention' {
	BeforeAll {
		# Load shared test helpers used by convention tests.
		$script:testHelpersPath = Join-Path $PSScriptRoot '..' '..' '..' 'conventions' 'scripts' 'TestHelpers.ps1'
		. $script:testHelpersPath
		$script:conventionScriptPath = Join-Path $PSScriptRoot 'convention.ps1'
	}

	It 'creates a conventions table from published convention README summaries' {
		# Create an isolated repository with two published conventions.
		$testDirectory = New-TemporaryDirectory

		try {
			[System.IO.File]::WriteAllText((Join-Path $testDirectory 'README.md'), "# Test`n`n## Sections`n`n* One`n", $utf8)
			[System.IO.Directory]::CreateDirectory((Join-Path $testDirectory 'conventions' 'alpha' 'files')) | Out-Null
			[System.IO.Directory]::CreateDirectory((Join-Path $testDirectory 'conventions' 'beta')) | Out-Null
			[System.IO.Directory]::CreateDirectory((Join-Path $testDirectory 'conventions' 'not-a-convention')) | Out-Null

			[System.IO.File]::WriteAllText((Join-Path $testDirectory 'conventions' 'alpha' 'README.md'), "# alpha`n`nManages [settings](files/settings.json) for alpha.`n", $utf8)
			[System.IO.File]::WriteAllText((Join-Path $testDirectory 'conventions' 'alpha' 'convention.yml'), "conventions: []`n", $utf8)
			[System.IO.File]::WriteAllText((Join-Path $testDirectory 'conventions' 'beta' 'README.md'), "# beta`n`nUpdates beta output.`n", $utf8)
			[System.IO.File]::WriteAllText((Join-Path $testDirectory 'conventions' 'beta' 'convention.ps1'), "Write-Host 'beta'`n", $utf8)
			[System.IO.File]::WriteAllText((Join-Path $testDirectory 'conventions' 'not-a-convention' 'README.md'), "# not-a-convention`n`nShould not appear.`n", $utf8)

			# Run the convention and verify it writes the generated table.
			$output = Invoke-ConventionScript -ScriptPath $script:conventionScriptPath -RepositoryRoot $testDirectory

			$expectedContent = "# Test`n`n## Sections`n`n* One`n`n## Conventions`n`n<!-- DO NOT EDIT: generated by .github/conventions/update-readme-conventions -->`n`n| Convention | Description |`n| --- | --- |`n| [alpha](./conventions/alpha/README.md) | Manages [settings](./conventions/alpha/files/settings.json) for alpha. |`n| [beta](./conventions/beta/README.md) | Updates beta output. |`n"
			Get-Content -LiteralPath (Join-Path $testDirectory 'README.md') -Raw | Should -Be $expectedContent
			$output[-1].ToString() | Should -Be "Updated 'README.md' with the current conventions table."
		}
		finally {
			# Remove the isolated repository after the test completes.
			Remove-Item -LiteralPath $testDirectory -Recurse -Force
		}
	}

	It 'replaces an existing conventions section and is idempotent' {
		# Create an isolated repository with an outdated conventions section.
		$testDirectory = New-TemporaryDirectory

		try {
			[System.IO.File]::WriteAllText((Join-Path $testDirectory 'README.md'), "# Test`n`n## Conventions`n`nOutdated content.`n`n## Other`n`nKeep this.`n", $utf8)
			[System.IO.Directory]::CreateDirectory((Join-Path $testDirectory 'conventions' 'alpha')) | Out-Null
			[System.IO.File]::WriteAllText((Join-Path $testDirectory 'conventions' 'alpha' 'README.md'), "# alpha`n`nManages alpha output.`n", $utf8)
			[System.IO.File]::WriteAllText((Join-Path $testDirectory 'conventions' 'alpha' 'convention.yml'), "conventions: []`n", $utf8)

			# Run the convention twice and verify the second run is a no-op.
			Invoke-ConventionScript -ScriptPath $script:conventionScriptPath -RepositoryRoot $testDirectory | Out-Null
			$secondOutput = Invoke-ConventionScript -ScriptPath $script:conventionScriptPath -RepositoryRoot $testDirectory

			$expectedContent = "# Test`n`n## Conventions`n`n<!-- DO NOT EDIT: generated by .github/conventions/update-readme-conventions -->`n`n| Convention | Description |`n| --- | --- |`n| [alpha](./conventions/alpha/README.md) | Manages alpha output. |`n`n## Other`n`nKeep this.`n"
			Get-Content -LiteralPath (Join-Path $testDirectory 'README.md') -Raw | Should -Be $expectedContent
			$secondOutput[-1].ToString() | Should -Be "'README.md' already contains the current conventions table."
		}
		finally {
			# Remove the isolated repository after the test completes.
			Remove-Item -LiteralPath $testDirectory -Recurse -Force
		}
	}
}
