#requires -PSEdition Core
#requires -Version 7.0
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$utf8 = [System.Text.UTF8Encoding]::new($false)
[Console]::InputEncoding = $utf8
[Console]::OutputEncoding = $utf8
$OutputEncoding = $utf8

# Load the shared managed text section helper used by section-owning conventions.
$configTextSectionPath = Join-Path $PSScriptRoot '..' '..' '..' 'conventions' 'scripts' 'ConfigTextSection.psm1'
Import-Module $configTextSectionPath

# Define the managed README table marker used by this convention.
$script:readmeConventionsSectionName = 'generated by .github/conventions/update-readme-conventions'

# Return the first prose paragraph after the README title.
function GetFirstParagraph {
	param(
		[Parameter(Mandatory = $true)]
		[string] $Path
	)

	$content = [System.IO.File]::ReadAllText($Path)
	$lines = ($content -replace "`r`n", "`n" -replace "`r", "`n") -split "`n"
	$index = 0

	while ($index -lt $lines.Count -and [string]::IsNullOrWhiteSpace($lines[$index])) {
		$index++
	}

	if ($index -lt $lines.Count -and $lines[$index] -match '^#\s+') {
		$index++
	}

	while ($index -lt $lines.Count -and [string]::IsNullOrWhiteSpace($lines[$index])) {
		$index++
	}

	$paragraphLines = [System.Collections.Generic.List[string]]::new()

	while ($index -lt $lines.Count -and -not [string]::IsNullOrWhiteSpace($lines[$index])) {
		$paragraphLines.Add($lines[$index].Trim())
		$index++
	}

	if ($paragraphLines.Count -eq 0) {
		throw "No first paragraph was found in '$Path'."
	}

	return ($paragraphLines -join ' ')
}

# Rewrite relative markdown links so README descriptions work from the repository root.
function ConvertDescriptionLinks {
	param(
		[Parameter(Mandatory = $true)]
		[string] $Text,

		[Parameter(Mandatory = $true)]
		[string] $ReadmeDirectory,

		[Parameter(Mandatory = $true)]
		[string] $RepositoryRoot
	)

	return [System.Text.RegularExpressions.Regex]::Replace(
		$Text,
		'(?<Prefix>\[[^\]]+\]\()(?<Target>[^)]+)(?<Suffix>\))',
		{
			param($match)

			$target = $match.Groups['Target'].Value

			if ($target -match '^[A-Za-z][A-Za-z0-9+.-]*:' -or $target.StartsWith('#', [System.StringComparison]::Ordinal) -or $target.StartsWith('/', [System.StringComparison]::Ordinal)) {
				return $match.Value
			}

			$anchor = ''
			$targetPath = $target
			$anchorIndex = $target.IndexOf('#')

			if ($anchorIndex -ge 0) {
				$anchor = $target.Substring($anchorIndex)
				$targetPath = $target.Substring(0, $anchorIndex)
			}

			if ([string]::IsNullOrWhiteSpace($targetPath)) {
				return $match.Value
			}

			$resolvedPath = [System.IO.Path]::GetFullPath((Join-Path $ReadmeDirectory $targetPath))
			$relativePath = [System.IO.Path]::GetRelativePath($RepositoryRoot, $resolvedPath).Replace('\', '/')

			if (-not $relativePath.StartsWith('.', [System.StringComparison]::Ordinal)) {
				$relativePath = './' + $relativePath
			}

			return $match.Groups['Prefix'].Value + $relativePath + $anchor + $match.Groups['Suffix'].Value
		})
}

# Escape markdown table delimiters in generated cell content.
function ConvertTableCell {
	param(
		[Parameter(Mandatory = $true)]
		[string] $Text
	)

	return $Text.Replace('|', '\|')
}

# Build convention table entries from published convention directories.
function GetConventionEntries {
	param(
		[Parameter(Mandatory = $true)]
		[string] $RepositoryRoot
	)

	$conventionsRoot = Join-Path $RepositoryRoot 'conventions'

	if (-not (Test-Path -LiteralPath $conventionsRoot -PathType Container)) {
		throw "The conventions directory was not found at '$conventionsRoot'."
	}

	$entries = [System.Collections.Generic.List[object]]::new()

	foreach ($conventionDirectory in Get-ChildItem -LiteralPath $conventionsRoot -Directory | Sort-Object -Property Name) {
		$readmePath = Join-Path $conventionDirectory.FullName 'README.md'
		$conventionYamlPath = Join-Path $conventionDirectory.FullName 'convention.yml'
		$conventionScriptPath = Join-Path $conventionDirectory.FullName 'convention.ps1'

		if (-not (Test-Path -LiteralPath $readmePath -PathType Leaf)) {
			continue
		}

		if (-not ((Test-Path -LiteralPath $conventionYamlPath -PathType Leaf) -or (Test-Path -LiteralPath $conventionScriptPath -PathType Leaf))) {
			continue
		}

		$description = GetFirstParagraph -Path $readmePath
		$description = ConvertDescriptionLinks -Text $description -ReadmeDirectory $conventionDirectory.FullName -RepositoryRoot $RepositoryRoot

		$entries.Add([pscustomobject]@{
			Name = $conventionDirectory.Name
			Path = ('./conventions/' + $conventionDirectory.Name + '/README.md')
			Description = $description
		})
	}

	return $entries.ToArray()
}

# Render the README conventions table body.
function NewConventionsTable {
	param(
		[Parameter(Mandatory = $true)]
		[object[]] $Entries
	)

	# Start the managed content directly with the table so surrounding README prose is preserved.
	$lines = [System.Collections.Generic.List[string]]::new()
	$lines.Add('| Convention | Description |')
	$lines.Add('| --- | --- |')

	foreach ($entry in $Entries) {
		$name = ConvertTableCell -Text $entry.Name
		$description = ConvertTableCell -Text $entry.Description
		$lines.Add("| [$name]($($entry.Path)) | $description |")
	}

	return ($lines -join "`n")
}

# Regenerate the root README conventions table.
$repositoryRoot = [System.IO.Path]::GetFullPath((Get-Location).Path)
$readmePath = Join-Path $repositoryRoot 'README.md'

if (-not (Test-Path -LiteralPath $readmePath -PathType Leaf)) {
	throw "The repository root README was not found at '$readmePath'."
}

$entries = GetConventionEntries -RepositoryRoot $repositoryRoot
$table = NewConventionsTable -Entries $entries

Invoke-ConfigTextSection -Settings @{
	path = 'README.md'
	name = $script:readmeConventionsSectionName
	text = $table
	'comment-prefix' = '<!--'
	'comment-suffix' = '-->'
}
