#requires -PSEdition Core
#requires -Version 7.0
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$utf8 = [System.Text.UTF8Encoding]::new($false)
[Console]::InputEncoding = $utf8
[Console]::OutputEncoding = $utf8
$OutputEncoding = $utf8

Describe 'faithlife-auto-apply-conventions convention' {
	BeforeAll {
		$script:conventionScriptPath = Join-Path $PSScriptRoot 'convention.ps1'
		$script:testHelpersPath = Join-Path $PSScriptRoot '..' 'scripts' 'TestHelpers.ps1'
		$script:requiredFirstLine = '# applied automatically by https://github.com/Faithlife/RepoConventionsApplier (DO NOT REMOVE THIS LINE)'
		. $script:testHelpersPath

		function script:InvokeAutoApplyConventionsConvention {
			param(
				[Parameter(Mandatory = $true)]
				[string] $TestDirectory
			)

			$inputPath = New-ConventionInputFile -Settings @{}

			Push-Location $TestDirectory
			try {
				return @(& $script:conventionScriptPath $inputPath 3>&1 6>&1)
			}
			finally {
				Pop-Location
				Remove-Item -LiteralPath $inputPath -ErrorAction SilentlyContinue
			}
		}

		function script:NewConventionsYamlFile {
			param(
				[Parameter(Mandatory = $true)]
				[string] $TestDirectory,

				[Parameter(Mandatory = $true)]
				[AllowEmptyString()]
				[string] $Content
			)

			$githubDirectory = Join-Path $TestDirectory '.github'
			[System.IO.Directory]::CreateDirectory($githubDirectory) | Out-Null

			$conventionsYamlPath = Join-Path $githubDirectory 'conventions.yml'
			Write-Utf8NoBomFile -Path $conventionsYamlPath -Content $Content
			return $conventionsYamlPath
		}
	}

	It 'fails when .github/conventions.yml is missing' {
		$testDirectory = New-TestDirectory

		try {
			Initialize-TestRepository -Path $testDirectory

			{ InvokeAutoApplyConventionsConvention -TestDirectory $testDirectory } | Should -Throw -ExpectedMessage "Expected '.github/conventions.yml' to exist."
		}
		finally {
			Remove-Item -LiteralPath $testDirectory -Recurse -Force
		}
	}

	It 'adds the marker as the first line when the file has normal content' {
		$testDirectory = New-TestDirectory

		try {
			Initialize-TestRepository -Path $testDirectory
			$conventionsYamlPath = NewConventionsYamlFile -TestDirectory $testDirectory -Content "conventions:`n  - path: Faithlife/CodingGuidelines/conventions/nuget-config`n"

			Push-Location $testDirectory
			try {
				& git add -A
				& git commit -m 'Add conventions file' | Out-Null
			}
			finally {
				Pop-Location
			}

			$output = InvokeAutoApplyConventionsConvention -TestDirectory $testDirectory
			$status = @(Get-GitStatusLines -TestDirectory $testDirectory)

			(Get-Content -LiteralPath $conventionsYamlPath -Raw) | Should -Be "$requiredFirstLine`nconventions:`n  - path: Faithlife/CodingGuidelines/conventions/nuget-config`n"
			$status.Count | Should -Be 1
			$status[0] | Should -Match '^ M \.github/conventions\.yml$'
			(@($output | ForEach-Object { $_.ToString() }) -contains "Added RepoConventionsApplier marker to '.github/conventions.yml'.") | Should -Be $true
		}
		finally {
			Remove-Item -LiteralPath $testDirectory -Recurse -Force
		}
	}

	It 'replaces an existing DO NOT REMOVE first line' {
		$testDirectory = New-TestDirectory

		try {
			Initialize-TestRepository -Path $testDirectory
			$conventionsYamlPath = NewConventionsYamlFile -TestDirectory $testDirectory -Content "# generated by old automation (DO NOT REMOVE)`nconventions:`n  - path: old/convention`n"

			$output = InvokeAutoApplyConventionsConvention -TestDirectory $testDirectory

			(Get-Content -LiteralPath $conventionsYamlPath -Raw) | Should -Be "$requiredFirstLine`nconventions:`n  - path: old/convention`n"
			(@($output | ForEach-Object { $_.ToString() }) -contains "Updated existing auto-apply marker in '.github/conventions.yml'.") | Should -Be $true
		}
		finally {
			Remove-Item -LiteralPath $testDirectory -Recurse -Force
		}
	}

	It 'preserves CRLF line endings when adding the marker' {
		$testDirectory = New-TestDirectory

		try {
			Initialize-TestRepository -Path $testDirectory
			$conventionsYamlPath = NewConventionsYamlFile -TestDirectory $testDirectory -Content "conventions:`r`n  - path: old/convention`r`n"

			InvokeAutoApplyConventionsConvention -TestDirectory $testDirectory | Out-Null

			(Get-Content -LiteralPath $conventionsYamlPath -Raw) | Should -Be "$requiredFirstLine`r`nconventions:`r`n  - path: old/convention`r`n"
		}
		finally {
			Remove-Item -LiteralPath $testDirectory -Recurse -Force
		}
	}

	It 'is idempotent when the marker is already present' {
		$testDirectory = New-TestDirectory

		try {
			Initialize-TestRepository -Path $testDirectory
			$conventionsYamlPath = NewConventionsYamlFile -TestDirectory $testDirectory -Content "$requiredFirstLine`nconventions:`n  - path: old/convention`n"

			Push-Location $testDirectory
			try {
				& git add -A
				& git commit -m 'Add marked conventions file' | Out-Null
				$headBeforeRun = & git rev-parse HEAD
			}
			finally {
				Pop-Location
			}

			$output = InvokeAutoApplyConventionsConvention -TestDirectory $testDirectory
			$headAfterRun = Get-CommitId -TestDirectory $testDirectory
			$status = @(Get-GitStatusLines -TestDirectory $testDirectory)

			(Get-Content -LiteralPath $conventionsYamlPath -Raw) | Should -Be "$requiredFirstLine`nconventions:`n  - path: old/convention`n"
			$headAfterRun | Should -Be $headBeforeRun
			$status.Count | Should -Be 0
			(@($output | ForEach-Object { $_.ToString() }) -contains "'.github/conventions.yml' already starts with the RepoConventionsApplier marker.") | Should -Be $true
		}
		finally {
			Remove-Item -LiteralPath $testDirectory -Recurse -Force
		}
	}
}
