# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Workflow that adds repository conventions to a specified repository and opens a pull request when needed.
name: Add Repository Conventions

on:
  workflow_dispatch:
    inputs:
      repository:
        type: string
        description: The owner/name of the repository to update, e.g. Faithlife/SomeRepo
        required: true
      conventions:
        type: string
        description: Space-delimited convention names to add, e.g. Faithlife/CodingGuidelines/conventions/repo-conventions-workflow
        required: true

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: repo-conventions-add-${{ inputs.repository }}
  cancel-in-progress: false

jobs:
  add:
    name: Add conventions
    uses: ./.github/workflows/repo-conventions-call.yml
    with:
      command: add
      repository: ${{ inputs.repository }}
      conventions: ${{ inputs.conventions }}
    secrets: inherit
